# Hugo configuration file
title: Memomo

# import hextra as module
theme: hextra

googleAnalytics: "G-HNH6BD1J9W"

defaultContentLanguage: ja
languages:
  ja:
    languageName: 日本語
    weight: 1

markup:
  # allow raw html
  goldmark:
    renderer:
      unsafe: true

  # enable hextra syntax highlight
  highlight:
    noClasses: false

menu:
  main:
    - name: Docs
      pageRef: /docs
      weight: 1
    - name: Blog
      pageRef: /blog
      weight: 2
    - name: Profile
      pageRef: /profile
      weight: 3
    - name: Search
      weight: 4
      params:
        type: search
    - name: GitHub
      weight: 5
      url: "https://github.com/physpeach"
      params:
        icon: github
    - name: Twitter
      weight: 6
      url: "https://twitter.com/physpeach"
      params:
        icon: twitter

params:
  navbar:
    displayTitle: true
    displayLogo: true
    logo:
      path: "favicon-64.png"

  page:
    width: "wide"

  footer:
    displayCopyright: true
    displayPoweredBy: true

  search:
    enable: true
    type: "flexsearch"
    flexsearch:
      index: content

  editURL:
    enable: true
    base: "https://github.com/physpeach/physpeach.github.io/edit/master/content"

  blog:
    list:
      displayCategories: true
      displayTags: true
