version: '3'
services:
  hugo:
    user: '${UID}:${GID}'
    image: 'klakegg/hugo:0.107.0-alpine'
    volumes:
      - '/etc/localtime:/etc/localtime:ro'
      - '/etc/group:/etc/group:ro'
      - '/etc/passwd:/etc/passwd:ro'
      - '.:/src'
  server:
    user: '${UID}:${GID}'
    image: 'klakegg/hugo:0.107.0-alpine'
    volumes:
      - '/etc/localtime:/etc/localtime:ro'
      - '/etc/group:/etc/group:ro'
      - '/etc/passwd:/etc/passwd:ro'
      - '.:/src'
    ports:
      - '${PORT}:${PORT}'
    command: 'server'
