version: '3'
services:
  builder:
    build: '.'
    image: 'gh-pages:latest'
    command: 'version'
  generator:
    user: '${UID}:${GID}'
    image: 'gh-pages:latest'
    volumes:
      - '/etc/localtime:/etc/localtime:ro'
      - '/etc/group:/etc/group:ro'
      - '/etc/passwd:/etc/passwd:ro'
      - '.:/src'
  server:
    user: '${UID}:${GID}'
    image: 'gh-pages:latest'
    volumes:
      - '/etc/localtime:/etc/localtime:ro'
      - '/etc/group:/etc/group:ro'
      - '/etc/passwd:/etc/passwd:ro'
      - '.:/src'
    ports:
      - '${PORT}:${PORT}'
    command: 'server'
