version: '3'
services:
  builder:
    build: '.'
    image: 'gh-pages:latest'
    command: 'version'
  generator:
    user: '${UID}:${GID}'
    image: 'gh-pages:latest'
    volumes:
      - '/etc/localtime:/etc/localtime:ro'
      - '/etc/group:/etc/group:ro'
      - '/etc/passwd:/etc/passwd:ro'
      - '.:/src'
    command: '--gc --minify --baseURL "https://physpeach.github.io"'
  server:
    user: '${UID}:${GID}'
    image: 'gh-pages:latest'
    volumes:
      - '/etc/localtime:/etc/localtime:ro'
      - '/etc/group:/etc/group:ro'
      - '/etc/passwd:/etc/passwd:ro'
      - '.:/src'
    ports:
      - '${PORT}:${PORT}'
    command: 'server --bind=0.0.0.0'
